@API_HostAddress = localhost:5229

###
GRPC {{API_HostAddress}}/Wealth.BuildingBlocks.InstrumentManagement.InstrumentsService/ChangePrice
Content-Type: application/grpc

{
    "id": {
        "id": { "value": "00000000-0000-0000-0000-000000000003" }
    },
    "price": {
        "currency_id": { "code": "RUB" },
        "price": { "units": "42", "nanos": 230000000 }
    }
}
