@API_HostAddress = http://localhost:5280/api

# @name Get currencies

GET {{API_HostAddress}}/Currency/
Accept: application/json

###

# @name Add FOO currency

POST {{API_HostAddress}}/Currency
Accept: application/json
Content-Type: application/json

{
  "id": "FOO",
  "name": "Foo",
  "symbol": "F"
}

###

# @name Add BAR currency

POST {{API_HostAddress}}/Currency
Accept: application/json
Content-Type: application/json

{
  "id": "BAR",
  "name": "Bar",
  "symbol": "B"
}


###

# @name Add exchange rate

POST {{API_HostAddress}}/ExchangeRate
Accept: application/json
Content-Type: application/json

{
  "fromId": "FOO",
  "toId": "BAR",
  "rate": 10,
  "date": "2010-10-10"
}

### 

# @name Convert FOO->BAR
GET {{API_HostAddress}}/ExchangeRate?fromId=FOO&toId=BAR&value=15.32&date=2010-10-10
Accept: application/json

###

# @name Rename currency

PUT {{API_HostAddress}}/Currency
Accept: application/json
Content-Type: application/json

{
  "id": "FOO",
  "newName": "Foo2"
}
