// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wealth.PortfolioManagement.Infrastructure.UnitOfWorks;

#nullable disable

namespace Wealth.PortfolioManagement.Infrastructure.Migrations
{
    [DbContext(typeof(WealthDbContext))]
    [Migration("20250715170602_OutboxKey")]
    partial class OutboxKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("PortfolioIdHiLo")
                .IncrementsBy(10);

            modelBuilder.Entity("Wealth.BuildingBlocks.Application.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Operations.CurrencyOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CurrencyOperations");
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Operations.InstrumentOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Portfolios.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "PortfolioIdHiLo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Portfolios.PortfolioAsset", b =>
                {
                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("PortfolioId", "InstrumentId");

                    b.ToTable("PortfolioAsset");
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Portfolios.PortfolioCurrency", b =>
                {
                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer");

                    b.Property<string>("CurrencyId")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.HasKey("PortfolioId", "CurrencyId");

                    b.ToTable("PortfolioCurrency");
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Operations.CashOperation", b =>
                {
                    b.HasBaseType("Wealth.PortfolioManagement.Domain.Operations.InstrumentOperation");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.ToTable("CashOperations", (string)null);
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Operations.DelistOperation", b =>
                {
                    b.HasBaseType("Wealth.PortfolioManagement.Domain.Operations.InstrumentOperation");

                    b.ToTable("DelistOperations", (string)null);
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Operations.SplitOperation", b =>
                {
                    b.HasBaseType("Wealth.PortfolioManagement.Domain.Operations.InstrumentOperation");

                    b.ToTable("SplitOperations", (string)null);
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Operations.TradeOperation", b =>
                {
                    b.HasBaseType("Wealth.PortfolioManagement.Domain.Operations.InstrumentOperation");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.ToTable("TradeOperations", (string)null);
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Operations.CurrencyOperation", b =>
                {
                    b.OwnsOne("Wealth.BuildingBlocks.Domain.Common.Money", "Money", b1 =>
                        {
                            b1.Property<Guid>("CurrencyOperationId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("CurrencyId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CurrencyOperationId");

                            b1.ToTable("CurrencyOperations");

                            b1.WithOwner()
                                .HasForeignKey("CurrencyOperationId");
                        });

                    b.Navigation("Money")
                        .IsRequired();
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Portfolios.PortfolioAsset", b =>
                {
                    b.HasOne("Wealth.PortfolioManagement.Domain.Portfolios.Portfolio", null)
                        .WithMany("Assets")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Portfolios.PortfolioCurrency", b =>
                {
                    b.HasOne("Wealth.PortfolioManagement.Domain.Portfolios.Portfolio", null)
                        .WithMany("Currencies")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Operations.CashOperation", b =>
                {
                    b.OwnsOne("Wealth.BuildingBlocks.Domain.Common.Money", "Money", b1 =>
                        {
                            b1.Property<Guid>("CashOperationId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("CurrencyId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CashOperationId");

                            b1.ToTable("CashOperations");

                            b1.WithOwner()
                                .HasForeignKey("CashOperationId");
                        });

                    b.Navigation("Money")
                        .IsRequired();
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Operations.SplitOperation", b =>
                {
                    b.OwnsOne("Wealth.PortfolioManagement.Domain.ValueObjects.SplitRatio", "Ratio", b1 =>
                        {
                            b1.Property<Guid>("SplitOperationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("New")
                                .HasColumnType("integer");

                            b1.Property<int>("Old")
                                .HasColumnType("integer");

                            b1.HasKey("SplitOperationId");

                            b1.ToTable("SplitOperations");

                            b1.WithOwner()
                                .HasForeignKey("SplitOperationId");
                        });

                    b.Navigation("Ratio")
                        .IsRequired();
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Operations.TradeOperation", b =>
                {
                    b.OwnsOne("Wealth.BuildingBlocks.Domain.Common.Money", "Money", b1 =>
                        {
                            b1.Property<Guid>("TradeOperationId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("CurrencyId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TradeOperationId");

                            b1.ToTable("TradeOperations");

                            b1.WithOwner()
                                .HasForeignKey("TradeOperationId");
                        });

                    b.Navigation("Money")
                        .IsRequired();
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Portfolios.Portfolio", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Currencies");
                });
#pragma warning restore 612, 618
        }
    }
}
