// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wealth.PortfolioManagement.Infrastructure.UnitOfWorks;

#nullable disable

namespace Wealth.PortfolioManagement.Infrastructure.Migrations
{
    [DbContext(typeof(WealthDbContext))]
    partial class WealthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("PortfolioIdHiLo")
                .IncrementsBy(10);

            modelBuilder.Entity("Wealth.BuildingBlocks.Application.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Application.Providers.PortfolioIdMap", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("text");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer");

                    b.HasKey("AccountId");

                    b.ToTable("PortfolioIdMaps", (string)null);
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Operations.Operation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("operation_type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("InstrumentOperations", (string)null);

                    b.HasDiscriminator<byte>("operation_type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Portfolios.BondAsset", b =>
                {
                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer");

                    b.Property<int>("BondId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("PortfolioId", "BondId");

                    b.ToTable("BondAsset", (string)null);
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Portfolios.CurrencyAsset", b =>
                {
                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer");

                    b.Property<byte>("CurrencyId")
                        .HasColumnType("smallint");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("PortfolioId", "CurrencyId");

                    b.ToTable("CurrencyAsset", (string)null);
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Portfolios.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "PortfolioIdHiLo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Portfolios", (string)null);
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Portfolios.PortfolioCurrency", b =>
                {
                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer");

                    b.Property<byte>("Currency")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.HasKey("PortfolioId", "Currency");

                    b.ToTable("PortfolioCurrency", (string)null);
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Portfolios.StockAsset", b =>
                {
                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("PortfolioId", "StockId");

                    b.ToTable("StockAsset", (string)null);
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Operations.BondAmortizationOperation", b =>
                {
                    b.HasBaseType("Wealth.PortfolioManagement.Domain.Operations.Operation");

                    b.Property<int>("BondId")
                        .HasColumnType("integer");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "Wealth.PortfolioManagement.Domain.Operations.BondAmortizationOperation.Amount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("numeric");

                            b1.Property<byte>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("smallint");
                        });

                    b.ToTable("InstrumentOperations", null, t =>
                        {
                            t.Property("BondId")
                                .HasColumnName("BondAmortizationOperation_BondId");

                            t.Property("PortfolioId")
                                .HasColumnName("BondAmortizationOperation_PortfolioId");
                        });

                    b.HasDiscriminator().HasValue((byte)1);
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Operations.BondCouponOperation", b =>
                {
                    b.HasBaseType("Wealth.PortfolioManagement.Domain.Operations.Operation");

                    b.Property<int>("BondId")
                        .HasColumnType("integer");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "Wealth.PortfolioManagement.Domain.Operations.BondCouponOperation.Amount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("numeric");

                            b1.Property<byte>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("smallint");
                        });

                    b.ToTable("InstrumentOperations", null, t =>
                        {
                            t.Property("BondId")
                                .HasColumnName("BondCouponOperation_BondId");

                            t.Property("PortfolioId")
                                .HasColumnName("BondCouponOperation_PortfolioId");
                        });

                    b.HasDiscriminator().HasValue((byte)6);
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Operations.CurrencyOperation", b =>
                {
                    b.HasBaseType("Wealth.PortfolioManagement.Domain.Operations.Operation");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "Wealth.PortfolioManagement.Domain.Operations.CurrencyOperation.Amount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("numeric");

                            b1.Property<byte>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("smallint");
                        });

                    b.HasDiscriminator().HasValue((byte)0);
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Operations.StockDelistOperation", b =>
                {
                    b.HasBaseType("Wealth.PortfolioManagement.Domain.Operations.Operation");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue((byte)4);
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Operations.StockDividendOperation", b =>
                {
                    b.HasBaseType("Wealth.PortfolioManagement.Domain.Operations.Operation");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "Wealth.PortfolioManagement.Domain.Operations.StockDividendOperation.Amount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("numeric");

                            b1.Property<byte>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("smallint");
                        });

                    b.ToTable("InstrumentOperations", null, t =>
                        {
                            t.Property("PortfolioId")
                                .HasColumnName("StockDividendOperation_PortfolioId");

                            t.Property("StockId")
                                .HasColumnName("StockDividendOperation_StockId");
                        });

                    b.HasDiscriminator().HasValue((byte)7);
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Operations.StockDividendTaxOperation", b =>
                {
                    b.HasBaseType("Wealth.PortfolioManagement.Domain.Operations.Operation");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "Wealth.PortfolioManagement.Domain.Operations.StockDividendTaxOperation.Amount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("numeric");

                            b1.Property<byte>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("smallint");
                        });

                    b.ToTable("InstrumentOperations", null, t =>
                        {
                            t.Property("PortfolioId")
                                .HasColumnName("StockDividendTaxOperation_PortfolioId");

                            t.Property("StockId")
                                .HasColumnName("StockDividendTaxOperation_StockId");
                        });

                    b.HasDiscriminator().HasValue((byte)8);
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Operations.StockSplitOperation", b =>
                {
                    b.HasBaseType("Wealth.PortfolioManagement.Domain.Operations.Operation");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Ratio", "Wealth.PortfolioManagement.Domain.Operations.StockSplitOperation.Ratio#SplitRatio", b1 =>
                        {
                            b1.Property<int>("New")
                                .HasColumnType("integer");

                            b1.Property<int>("Old")
                                .HasColumnType("integer");
                        });

                    b.ToTable("InstrumentOperations", null, t =>
                        {
                            t.Property("StockId")
                                .HasColumnName("StockSplitOperation_StockId");
                        });

                    b.HasDiscriminator().HasValue((byte)5);
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Operations.TradeOperation", b =>
                {
                    b.HasBaseType("Wealth.PortfolioManagement.Domain.Operations.Operation");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "Wealth.PortfolioManagement.Domain.Operations.TradeOperation.Amount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("numeric");

                            b1.Property<byte>("Currency")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("smallint");
                        });

                    b.ToTable("InstrumentOperations", null, t =>
                        {
                            t.Property("PortfolioId")
                                .HasColumnName("TradeOperation_PortfolioId");

                            t.Property("Type")
                                .HasColumnName("TradeOperation_Type");
                        });
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Operations.BondTradeOperation", b =>
                {
                    b.HasBaseType("Wealth.PortfolioManagement.Domain.Operations.TradeOperation");

                    b.Property<int>("BondId")
                        .HasColumnType("integer");

                    b.ToTable("InstrumentOperations", null, t =>
                        {
                            t.Property("PortfolioId")
                                .HasColumnName("TradeOperation_PortfolioId");

                            t.Property("Type")
                                .HasColumnName("TradeOperation_Type");
                        });

                    b.HasDiscriminator().HasValue((byte)2);
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Operations.StockTradeOperation", b =>
                {
                    b.HasBaseType("Wealth.PortfolioManagement.Domain.Operations.TradeOperation");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.ToTable("InstrumentOperations", null, t =>
                        {
                            t.Property("PortfolioId")
                                .HasColumnName("TradeOperation_PortfolioId");

                            t.Property("Type")
                                .HasColumnName("TradeOperation_Type");

                            t.Property("StockId")
                                .HasColumnName("StockTradeOperation_StockId");
                        });

                    b.HasDiscriminator().HasValue((byte)3);
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Portfolios.BondAsset", b =>
                {
                    b.HasOne("Wealth.PortfolioManagement.Domain.Portfolios.Portfolio", null)
                        .WithMany("Bonds")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Portfolios.CurrencyAsset", b =>
                {
                    b.HasOne("Wealth.PortfolioManagement.Domain.Portfolios.Portfolio", null)
                        .WithMany("CurrencyAssets")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Portfolios.PortfolioCurrency", b =>
                {
                    b.HasOne("Wealth.PortfolioManagement.Domain.Portfolios.Portfolio", null)
                        .WithMany("Currencies")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Portfolios.StockAsset", b =>
                {
                    b.HasOne("Wealth.PortfolioManagement.Domain.Portfolios.Portfolio", null)
                        .WithMany("Stocks")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wealth.PortfolioManagement.Domain.Portfolios.Portfolio", b =>
                {
                    b.Navigation("Bonds");

                    b.Navigation("Currencies");

                    b.Navigation("CurrencyAssets");

                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
