// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wealth.StrategyTracking.Infrastructure.UnitOfWorks;

#nullable disable

namespace Wealth.StrategyTracking.Infrastructure.Migrations
{
    [DbContext(typeof(WealthDbContext))]
    [Migration("20250905202047_Fix_Refactor")]
    partial class Fix_Refactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("StrategyIdHiLo")
                .IncrementsBy(10);

            modelBuilder.Entity("Wealth.BuildingBlocks.Application.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("Wealth.StrategyTracking.Domain.Strategies.Strategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "StrategyIdHiLo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Strategies");
                });

            modelBuilder.Entity("Wealth.StrategyTracking.Domain.Strategies.StrategyComponent", b =>
                {
                    b.Property<int>("StrategyId")
                        .HasColumnType("integer");

                    b.Property<byte>("type")
                        .HasColumnType("smallint");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("StrategyId", "type", "Id");

                    b.ToTable("StrategyComponent");

                    b.HasDiscriminator<byte>("type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Wealth.StrategyTracking.Domain.Strategies.BondStrategyComponent", b =>
                {
                    b.HasBaseType("Wealth.StrategyTracking.Domain.Strategies.StrategyComponent");

                    b.Property<int>("BondId")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue((byte)1);
                });

            modelBuilder.Entity("Wealth.StrategyTracking.Domain.Strategies.CurrencyStrategyComponent", b =>
                {
                    b.HasBaseType("Wealth.StrategyTracking.Domain.Strategies.StrategyComponent");

                    b.Property<byte>("CurrencyId")
                        .HasColumnType("smallint");

                    b.HasDiscriminator().HasValue((byte)2);
                });

            modelBuilder.Entity("Wealth.StrategyTracking.Domain.Strategies.StockStrategyComponent", b =>
                {
                    b.HasBaseType("Wealth.StrategyTracking.Domain.Strategies.StrategyComponent");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue((byte)0);
                });

            modelBuilder.Entity("Wealth.StrategyTracking.Domain.Strategies.StrategyComponent", b =>
                {
                    b.HasOne("Wealth.StrategyTracking.Domain.Strategies.Strategy", null)
                        .WithMany("Components")
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wealth.StrategyTracking.Domain.Strategies.Strategy", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
