@API = http://localhost:5018
@portfolioId = 00000000-0000-0000-0000-000000000001

GET {{API}}/api/portfolio/
Accept: application/json

###

GET {{API}}/api/portfolio/{{portfolioId}}
Accept: application/json

###