@API = http://localhost:5018
@portfolioId = 2
@name = Test3

GET {{API}}/api/portfolio/
Accept: application/json

###

GET {{API}}/api/portfolio/{{portfolioId}}
Accept: application/json

###

POST {{API}}/api/portfolio
Accept: application/json
Content-Type: application/json

{
  "name": "{{name}}"
}

###

PUT {{API}}/api/portfolio/deposit
Accept: application/json
Content-Type: application/json

{
  "portfolioId": "{{portfolioId}}",
  "money": {
    "CurrencyId" : { "code":  "RUB" },
     "Amount" : "22.34"
  }
}
