// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wealth.Aggregation.Infrastructure.UnitOfWorks;

#nullable disable

namespace Wealth.Aggregation.Infrastructure.Migrations
{
    [DbContext(typeof(WealthDbContext))]
    [Migration("20250919165249_Refactor")]
    partial class Refactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wealth.Aggregation.Domain.StockAggregation", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("LotSize")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.ComplexProperty<Dictionary<string, object>>("DividendPerYear", "Wealth.Aggregation.Domain.StockAggregation.DividendPerYear#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<byte>("CurrencyId")
                                .HasColumnType("smallint");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("StockPrice", "Wealth.Aggregation.Domain.StockAggregation.StockPrice#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<byte>("CurrencyId")
                                .HasColumnType("smallint");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TotalDividends", "Wealth.Aggregation.Domain.StockAggregation.TotalDividends#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<byte>("CurrencyId")
                                .HasColumnType("smallint");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TotalInvestments", "Wealth.Aggregation.Domain.StockAggregation.TotalInvestments#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<byte>("CurrencyId")
                                .HasColumnType("smallint");
                        });

                    b.HasKey("Id");

                    b.ToTable("StockAggregations");
                });

            modelBuilder.Entity("Wealth.BuildingBlocks.Application.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
