@API = http://localhost:5002
@portfolioId = 2
@name = Test3

GET {{API}}/api/portfolio/
Accept: application/json

###

GET {{API}}/api/portfolio/{{portfolioId}}
Accept: application/json

###

POST {{API}}/api/portfolio
Accept: application/json
Content-Type: application/json

{
  "name": "{{name}}"
}

###

PUT {{API}}/api/portfolio/deposit
Accept: application/json
Content-Type: application/json

{
  "portfolioId": "{{portfolioId}}",
  "money": {
    "CurrencyId" : { "code":  "RUB" },
     "Amount" : "22.34"
  }
}

###

PUT {{API}}/api/portfolio/{{portfolioId}}/asset
Accept: application/json
Content-Type: application/json

{
  "InstrumentId": {
    "Id": "00000000-0000-0000-0000-000000000003"
  },
  "TotalPrice": {
    "CurrencyId": { "code":  "RUB" },
    "Amount": "22.34"
  },
  "quantity": 4
}